import React from 'react';
import {
  Home, User, Settings, Heart, Star, Search, Mail, Phone, Calendar, Camera, Edit, Trash, Plus, Minus, X, Zap, Move, RotateCcw, Save, Paintbrush, Ruler, Image, HelpCircle,
  Check as CheckIconComponent,
  RefreshCw as RefreshCwIconComponent,
  Activity, AlertCircle, Archive, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AtSign, Award, Bell, Bookmark, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, Clipboard, Clock, Cloud, Code, Command, CreditCard, Database, Disc, Download, ExternalLink, File, Filter, Flag, Folder, Gift, Globe, Grid, HardDrive, Hash, Headphones, Inbox, Info, Key, Layers, LifeBuoy, Link, List, Lock, LogIn, LogOut, Map, Menu, MessageCircle, MessageSquare, Mic, Monitor, Moon, MoreHorizontal, MoreVertical, MousePointer, Music, Navigation, Package, Paperclip, Pause, PenTool, Play, Power, Printer, QrCode, Repeat, Rss, Scissors, Send, Share, Shield, ShoppingBag, ShoppingCart, Sun, Tag, Target, Terminal, ThumbsDown, ThumbsUp, ToggleLeft, ToggleRight, TrendingDown, TrendingUp, Truck, Tv, Umbrella, Unlock, Upload, Users, Video, Voicemail, Volume1, Volume2, VolumeX, Wallet, Watch, Wifi, ZoomIn, ZoomOut
} from 'lucide-react';

// This map must match the names used in ComponentEditor.tsx
const ICONS: Record<string, React.ElementType> = {
  home: Home,
  user: User,
  settings: Settings,
  heart: Heart,
  star: Star,
  search: Search,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  camera: Camera,
  edit: Edit,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  checkIcon: CheckIconComponent,
  x: X,
  zap: Zap,
  refreshCw: RefreshCwIconComponent,
  move: Move,
  rotateCcw: RotateCcw,
  save: Save,
  paintbrush: Paintbrush,
  ruler: Ruler,
  image: Image,
  activity: Activity,
  alertCircle: AlertCircle,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  atSign: AtSign,
  award: Award,
  bell: Bell,
  bookmark: Bookmark,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  command: Command,
  creditCard: CreditCard,
  database: Database,
  disc: Disc,
  download: Download,
  externalLink: ExternalLink,
  file: File,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  gift: Gift,
  globe: Globe,
  grid: Grid,
  hardDrive: HardDrive,
  hash: Hash,
  headphones: Headphones,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  lifeBuoy: LifeBuoy,
  link: Link,
  list: List,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  map: Map,
  menu: Menu,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  mousePointer: MousePointer,
  music: Music,
  navigation: Navigation,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  penTool: PenTool,
  play: Play,
  power: Power,
  printer: Printer,
  qrCode: QrCode,
  repeat: Repeat,
  rss: Rss,
  scissors: Scissors,
  send: Send,
  share: Share,
  shield: Shield,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  sun: Sun,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  truck: Truck,
  tv: Tv,
  umbrella: Umbrella,
  unlock: Unlock,
  users: Users,
  video: Video,
  voicemail: Voicemail,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
};

type IconProps = {
  name: keyof typeof ICONS | string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  className?: string;
};

const Icon: React.FC<IconProps & React.SVGProps<SVGSVGElement>> = ({ name, size = 20, color, strokeWidth, className, ...props }) => {
  const Component = ICONS[name] ?? HelpCircle;
  return <Component size={size} color={color} strokeWidth={strokeWidth} className={className} {...props} />;
};

export default Icon;

